package com.example.keniphhomemaintenance

object Dimens {

    const val ADD_MAINTENANCE_ITEM_BUTTON_SIZE = 50
    const val MAINTENANCE_ITEM_DIALOG_VERTICAL_PADDING = 200
    const val MAINTENANCE_ITEM_DIALOG_CORNER_RADIUS = 25
    const val MAINTENANCE_ITEM_DIALOG_TOP_PADDING = 15
    const val MAINTENANCE_ITEM_CARD_TITLE_TEXT_SIZE = 25
    const val MAINTENANCE_ITEM_DIALOG_TITLE_BOTTOM_PADDING = 7.5
    const val MAINTENANCE_ITEM_DIALOG_PADDING_BETWEEN_TEXT_FIELDS = 5
    const val MAINTENANCE_ITEM_DIALOG_LOCATION_FIELD_BOTTOM_PADDING = 15
    const val MAINTENANCE_TITLE_AND_DUE_DATE_PADDING = 4
    const val MAINTENANCE_CARD_START_PADDING = 7.5
    const val MAINTENANCE_CARD_ROW_VERTICAL_PADDING = 7.5
    const val MAINTENANCE_CARD_ROW_START_PADDING = 15
    const val MAINTENANCE_IMAGE_SIZE = 40
    const val MAINTENANCE_IMAGE_END_PADDING = 15
    const val MAINTENANCE_ITEM_LIST_BOTTOM_PADDING = 70
}