package com.example.keniphhomemaintenance

import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

object Dimens {

    val MAINTENANCE_ITEM_DIALOG_CORNER_RADIUS = 25.dp
    val MAINTENANCE_ITEM_DIALOG_TOP_PADDING = 15.dp
    val MAINTENANCE_ITEM_CARD_TITLE_TEXT_SIZE = 25.sp
    val MAINTENANCE_ITEM_DIALOG_TITLE_BOTTOM_PADDING = 7.5.dp
    val MAINTENANCE_ITEM_DIALOG_PADDING_BETWEEN_TEXT_FIELDS = 5.dp
    val MAINTENANCE_ITEM_DIALOG_LOCATION_FIELD_BOTTOM_PADDING = 15.dp
    val MAINTENANCE_TITLE_AND_DUE_DATE_PADDING = 4.dp
    val MAINTENANCE_CARD_START_PADDING = 7.5.dp
    val MAINTENANCE_CARD_ROW_VERTICAL_PADDING = 7.5.dp
    val MAINTENANCE_CARD_ROW_START_PADDING = 15.dp
    val MAINTENANCE_IMAGE_SIZE = 40.dp
    val MAINTENANCE_IMAGE_END_PADDING = 15.dp
    val MAINTENANCE_ITEM_LIST_BOTTOM_PADDING = 70.dp
    val NEW_DWELLING_TEXT_SIZE = 25.sp

    val LAZY_COLUMN_BOTTOM_PADDING = 100.dp
    val LAZY_COLUMN_HOR_CONTENT_PADDING = 16.dp
    val LAZY_COLUMN_VERT_CONTENT_PADDING = 8.dp

    val DWELLING_ITEM_CARD_PADDING = 8.dp
    val DWELLING_ITEM_CARD_ELEVATION = 2.dp
    val DWELLING_ITEM_COLUMN_PADDING = 16.dp

    val DIALOG_PADDING = 16.dp

    val FLOATING_ACTION_BUTTON_SIZE = 50.dp

    val BUTTON_PADDING = 16.dp

    val CARD_CORNER_RADIUS = 16.dp

}